version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59
    shm_size: "1gb"
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    volumes:
      - ./downloads:/home/seluser/Downloads  
  firefox:
    image: selenium/node-firefox:3.141.59
    shm_size: "1gb"
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    volumes:
      - ./downloads:/home/seluser/Downloads  
  searchmodule:
    image: revanth9/selenium-docker:latest
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=search-module.xml
    volumes:
      - ./output/search-result:/usr/share/udemy/test-output
  bookflightmodule:
    image: revanth9/selenium-docker:latest
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=book-flight-module.xml
    volumes:
      - ./output/book-flight-module:/usr/share/udemy/test-output